### ISSUE TITLE
How should I install splitfa

### ISSUE THREAD

**Issue by zhaotao1987** [ekg/splitfa#1]
@ekg  Hi Erik, I've searched your tool 'splitfa' in order to divide my fasta sequence into pieces. But I've no idea how to install and use this Rust App. I know nothing about Rust. Could you give me some clue, thanks! Best, Tao

**Comment by ekg** [comment]
You'll want to get rust set up on your system. Then, you can run this `cargo install --force --path .` to install splitfa in your user's rust path. You can also do `cargo build --release` and the executable will be `target/release/splitfa` in the repository directory.

**Comment by zhaotao1987** [comment]
Super, worked! Thanks a lot.
